### ISSUE TITLE
unable to connect to twitch.

### ISSUE THREAD

**Issue by imFlipp** [lindstrm/twitcha#13]
After logging in I get a plain text message involving which is something along the lines of "<redirect="http://api.twitch" and nothing happens.

**Comment by lindstrm** [comment]
Is it still an issue? Might have been something on Twitch's end.

**Comment by jmaartenson** [comment]
I get the same issue, {"redirect":"https://secure.twitch.tv/passport/callback?client_id=... etcetera etcetera, and it never redirects to you.

**Comment by lindstrm** [comment]
Ok, thanks! I'll look into it.

**Comment by lindstrm** [comment]
Seems to be an issue with Twitch.
https://github.com/justintv/Twitch-API/issues/574

**Comment by lindstrm** [comment]
Yep, Twitch changed the way you login using OAuth without even documenting it... :clap:

**Comment by V1an** [comment]
I wanted to raise the same issue, instead of that, i want to thanks you for this great tool, I can finally watch twitch on my old computer with more than 5 IPS :D

**Comment by lindstrm** [comment]
Thanks @V1an :)
The issue should be resolved with the latest update.

**Comment by adriancretu** [comment]
Hi. Can I ask how you fixed this? Is there a documented change somewhere, or did you redirected yourself to the URL from the JSON response? (which qualifies as a dirty hack in my opinion). I noticed that a bad username or password also responds with a JSON instead of showing up an error page. The Twitch staff seems to be on vacation when it comes to obvious bugs in their own API.

**Comment by lindstrm** [comment]
@adriancretu Took a while to figure out, but the login page couldn't load jQuery, so in my case it worked when I disabled node integration for that window and then it worked as before.
